-- ELIMINAR BANCOS ANTERIORES E CRIAR UM NOVOS
DROP DATABASE IF EXISTS VENDAS_SUCOS;
DROP DATABASE IF EXISTS SUCOS_VENDAS;
CREATE DATABASE IF NOT exists VENDAS_SUCOS;
CREATE DATABASE IF NOT exists SUCOS_VENDAS;

-- SELECIONAR BANCO DE DADOS CRIADO
USE VENDAS_SUCOS;

-- CRIAR TABELA DE PRODUTOS 
CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

-- CRIAR TABELA DE VENDEDORES
CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA));

-- CORRIGIR NOME DE COLUNA ERRADO 
ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

-- CRIAR TABELA DE CLIENTES
CREATE TABLE CLIENTES
( CPF VARCHAR (11) ,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
IDADE SMALLINT,
SEXO VARCHAR (1) ,
LIMITE_CREDITO FLOAT ,
VOLUME_COMPRA FLOAT ,
PRIMEIRA_COMPRA BIT ,
PRIMARY KEY (CPF));

-- CRIAR TABELA DE VENDAS 
CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

-- RELACIONAR TABELA DE VENDAS COM VENDEDORES E CLIENTES 
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

-- RENOMEAR TABELA DE VENDAS
ALTER TABLE tabela_de_vendas RENAME Notas;