-- Criar banco de de dados-->Administration-->Data import 
-- SELECIONAR BANCO DE DADOS 
USE vendas_sucos;
-- SELECIONAR TABELA DE OUTRO BANCO DE DADOS 
SELECT * FROM sucos_vendas.tabela_de_produtos;

-- QUERY (EVITAR CPF REPETIDO NOS BANCOS DE DADOS)
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR,
EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

--  INSERIR DADOS DE UMA BANCO DE DADOS EXTERNO (PRODUTOS)
INSERT INTO produtos
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR,
SABOR, TAMANHO, EMBALAGEM,  PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);
-- EXIBIR
SELECT * FROM produtos;

--  INSERIR DADOS DE UMA BANCO DE DADOS EXTERNO (PRODUTOS)
INSERT INTO CLIENTES (CPF,NOME, ENDERECO1, ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,IDADE,SEXO,LIMITE_CREDITO,PRIMEIRA_COMPRA ) 
SELECT CPF, NOME, ENDERECO_1,ENDERECO_2,BAIRRO,CIDADE,ESTADO,CEP,IDADE,SEXO,LIMITE_DE_CREDITO,PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes WHERE CPF
NOT IN (SELECT CPF FROM CLIENTES);

-- EXIBIR
SELECT * FROM clientes;
SHOW COLUMNS FROM  clientes;

SELECT * FROM sucos_vendas.tabela_de_clientes;
SHOW COLUMNS FROM sucos_vendas.tabela_de_clientes;

-- selecionar banco de dados-->selecionar tabela--> import wizard-->impor csv
