-- SELECIONAR BANCO DE DADOS 
USE vendas_sucos;
-- EXIBIR
SELECT * FROM produtos;

-- MUDAR 1 VALOR DE 1 REGISTROS
UPDATE produtos SET PRECO_LISTA = 5 WHERE CODIGO = '1000889';
-- EXIBIR
SELECT * FROM produtos WHERE CODIGO = '1000889' ;

-- MUDAR VÁRIOS VALORES DE 1 REGISTROS
UPDATE produtos SET EMBALAGEM = 'PET', TAMANHO = '1 Litro', DESCRITOR ='Sabor da Montanha - 1 Litro - Uva' WHERE CODIGO = '1000889';
-- EXIBIR
SELECT * FROM produtos WHERE CODIGO = '1000889';

-- MUDAR 1 VALOR DE VÁRIOS REGISTROS 
UPDATE produtos SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'Maracujá';
-- EXIBIR
SELECT * FROM produtos WHERE SABOR = 'Maracujá';

-- ANEXAR UM COULNA DE REGISTROS DE UMA BASE EXTERNA
-- EXIBIR
SELECT * FROM VENDEDORES A INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);
--
UPDATE VENDEDORES A INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3) -- > PEGAR SÓ OS VALORES DIFERENTES DE 0
SET A.FERIAS = B.DE_FERIAS;
-- EXIBIR
SELECT * FROM VENDEDORES;