 -- SELECIONAR BANCO DE DADOS 
USE vendas_sucos;
-- CRIAR UMA TRANSAÇÃO 
START TRANSACTION;
--
--
-- MODIFICAÇÃO ALETÓRIA 
 UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.15;
 -- ALTERAÇÃO TEMPORÁRIA 
SELECT * FROM VENDEDORES;

-- FINALIZAR TRANSAÇÃO E DESCONSIDERAR ALTERAÇÕES
ROLLBACK;
-- COMO FOI GRAVADO 
SELECT * FROM VENDEDORES;

-- ---------------------------------------------------
-- CRIAR UMA TRANSAÇÃO 
START TRANSACTION;
UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.15;
SELECT * FROM VENDEDORES;
COMMIT;
SELECT * FROM VENDEDORES;



