 -- SELECIONAR BANCO DE DADOS 
USE vendas_sucos;

-- AUTOENCREMENTO 
-- TABELA 
CREATE  TABLE IF NOT EXISTS TAB_IDENTITY 
(ID INT AUTO_INCREMENT, 
DESCRITOR VARCHAR(20), 
PRIMARY KEY(ID));

-- TESTE
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE1');
SELECT * FROM TAB_IDENTITY;

-- TESTE 
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE2');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE3');
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE4');
SELECT * FROM TAB_IDENTITY;

-- DELETAR BESEADO NO ID
DELETE FROM TAB_IDENTITY WHERE ID = 2;
SELECT * FROM TAB_IDENTITY;

-- TENTAR RECOLOCAR 
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE2');
SELECT * FROM TAB_IDENTITY;

-- FORÇAR A MUDANÇA DO CONTADOR (SEMPRE DO ULTIMO REGISTRO)
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (100, 'CLIENTE5');
SELECT * FROM TAB_IDENTITY;