 -- SELECIONAR BANCO DE DADOS 
USE vendas_sucos;
-- TABELA 
CREATE TABLE IF NOT EXISTS TAB_PADRAO
(ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20),
ENDERECO VARCHAR(100) NULL,
CIDADE   VARCHAR(50) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(ID));

-- INSERIR COM DETALHAMENTO
INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2019-01-01');
SELECT * FROM TAB_PADRAO;

-- INSERIR LIVRE
INSERT INTO TAB_PADRAO (DESCRITOR) VALUES ('CLIENTE Y');
SELECT * FROM TAB_PADRAO;

-- ORGANIZAR POR ORDEM CRONOLIGICO 
select *from TAB_PADRAO ORDER BY DATA_CRIACAO DESC;