function convergencia(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 04-May-2019 20:46:09

% Create figure
figure1 = figure('Name','CONVERGÊNCIA','Color',[1 1 1]);
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create semilogx
semilogx(X1,Y1,'LineWidth',1,'Color',[1 0 0]);

% Create ylabel
ylabel('CARGA CRÍTICA   (kN)');

% Create xlabel
xlabel('Nº DE ITERAÇÕES');

% Create title
title('CURVA DE CONVERGÊNCIA DO PSO');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
