-- N° ALETÓRIO 
SELECT FLOOR(RAND()*100);
SELECT MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS ;

-- GERAR NUMERO ALETÓRIO 
SELECT f_numero_aleatorio(10,100 );

-- USUÁRIO ALETÓRIO 
SELECT f_cliente_aleatorio();

-- USUÁRIO , PRODUTO E VENDEDOR ALETÓRIOS 
SELECT f_cliente_aleatorio(), f_produto_aleatorio(), f_vendedor_aleatorio();

-- SP COM FUNÇÃO 
CALL sp_inserir_venda_2('20190517', 1, 100);
-- VERIFICAR
SELECT A.NUMERO, COUNT(*) AS NUMERO_INTENS,SUM( B.QUANTIDADE * B.PRECO) AS FATURA 
FROM NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO=B.NUMERO
WHERE A.DATA_VENDA='20190517'
GROUP BY A.NUMERO ;

