function diferenca_relativa(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Mar-2019 14:15:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogx
MinLocal1=islocalmin(YMatrix1(:,2));
MinLocal2=islocalmin(YMatrix1(:,3));

semilogx1 = semilogx(X1,YMatrix1,X1(MinLocal1),YMatrix1(MinLocal1,2),'*r',X1(MinLocal2),YMatrix1(MinLocal2,3),'*r','Parent',axes1);
set(semilogx1(1),'DisplayName','Erro Relativo','LineWidth',1);
set(semilogx1(2),'DisplayName','Faixas','LineWidth',2.5,'LineStyle','--');
set(semilogx1(3),'DisplayName','CUFSM','LineWidth',1.2);

% Create ylabel
ylabel('P_c_r / P_m_a_x');

% Create xlabel
xlabel('Comprimento');

% Create title
title({'Diferença Relativa'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log');
% Create legend
legend(axes1,'show');

